### ISSUE TITLE
invalid or corrupt torrent file

### ISSUE THREAD

**Issue by vipera7** [transmission-php/transmission-php#17]
I'm having an issue when I add a torrent.  I add a file path or a url :

```
if (file_exists("testfile.torrent")) {
    $torrent = $transmission->add("testfile.torrent");
}
```
I get the following error : 

```
PHP Fatal error:  Uncaught RuntimeException: An error occured: "invalid or corrupt torrent file" in /root/seedbox/vendor/kleiram/transmission-php/lib/Transmission/Util/ResponseValidator.php:21
Stack trace:
#0 /root/seedbox/vendor/kleiram/transmission-php/lib/Transmission/Transmission.php(176): Transmission\Util\ResponseValidator::validate()
#1 /root/seedbox/test.php(58): Transmission\Transmission->add()
#2 {main}
  thrown in /root/seedbox/vendor/kleiram/transmission-php/lib/Transmission/Util/ResponseValidator.php on line 21
```

I tested the file by adding directly the web interface and it's working fine. I don't know where the issue is.

Thanks for any help

**Comment by toto4ds** [comment]
try 
`$transmission->add(base64_encode(file_get_contents($torrent)), true);`
